### ISSUE TITLE
downscaled and optimized versions?

### ISSUE THREAD

**Issue by TheFantasticLoki** [osuperu/osuperu-gosumemory-overlay#1]
Can you please make a version that is downscaled to 720p or similar to remove some overhead on gameoverlay. my input delay goes from 0.4 to 2.2ms just by using this overlay in game. But I very much enjoy this overlay and what it offers. Maybe also making the size only to the edge of the live pp as well to reduce the amount of px rendered since gameoverlay also renders the transparent px.

**Comment by TheFantasticLoki** [comment]
changing gameoverlay width to 1400 keeps all elements in gameplay overlay and reduced input delay to 1.5-1.6ms

**Comment by 7mochi** [comment]
Sorry for the delay, so can I close this issue or do you still want a downscaled version?
